package report

import (
    "encoding/json"
    "fmt"
    "os"
    "strings"
    "time"
)

type ReportData struct {
    Target         string
    StartTime      time.Time
    EndTime        time.Time
    Duration       string
    Subdomains     []string
    LiveHosts      []string
    URLs           []string
    Vulnerabilities []Vulnerability
    OpenPorts      []Port
    Technologies   []Technology
}

type Vulnerability struct {
    URL        string
    TemplateID string
    Severity   string
    Name       string
    CVSS       float64
}

type Port struct {
    Host    string
    Port    int
    Service string
}

type Technology struct {
    URL   string
    Name  string
    Version string
}

type Generator struct {
    outputDir string
}

func NewGenerator(outputDir string) *Generator {
    return &Generator{
        outputDir: outputDir,
    }
}

func (g *Generator) Generate(data *ReportData) error {
    if err := g.generateJSON(data); err != nil {
        return err
    }
    if err := g.generateMarkdown(data); err != nil {
        return err
    }
    if err := g.generateHTML(data); err != nil {
        return err
    }
    return nil
}

func (g *Generator) generateJSON(data *ReportData) error {
    filePath := g.outputDir + "/report.json"
    jsonData, err := json.MarshalIndent(data, "", "  ")
    if err != nil {
        return err
    }
    return os.WriteFile(filePath, jsonData, 0644)
}

func (g *Generator) generateMarkdown(data *ReportData) error {
    filePath := g.outputDir + "/README.md"
    content := fmt.Sprintf(`# ReconForge Scan Report

**Target:** %s
**Date:** %s
**Duration:** %s

## Summary

| Metric | Value |
|--------|-------|
| Subdomains | %d |
| Live Hosts | %d |
| URLs | %d |
| Vulnerabilities | %d |

## Live Hosts

%s

## Vulnerabilities

%s

---
*Generated by ReconForge*
`,
        data.Target,
        time.Now().Format("2006-01-02 15:04:05"),
        data.Duration,
        len(data.Subdomains),
        len(data.LiveHosts),
        len(data.URLs),
        len(data.Vulnerabilities),
        strings.Join(data.LiveHosts, "\n"),
        g.formatVulnerabilities(data.Vulnerabilities),
    )
    return os.WriteFile(filePath, []byte(content), 0644)
}

func (g *Generator) formatVulnerabilities(vulns []Vulnerability) string {
    if len(vulns) == 0 {
        return "No vulnerabilities found"
    }
    var result []string
    for _, v := range vulns {
        result = append(result, fmt.Sprintf("- [%s] %s: %s (CVSS: %.1f)", v.Severity, v.TemplateID, v.Name, v.CVSS))
    }
    return strings.Join(result, "\n")
}
