package report

import (
    "fmt"
    "os"
    "strings"
    "time"
)

func (g *Generator) generateHTML(data *ReportData) error {
    filePath := g.outputDir + "/report.html"
    
    htmlContent := fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
    <title>ReconForge Report - %s</title>
    <meta charset="UTF-8">
    <style>
        body { background: #0a0e27; color: #e0e0e0; font-family: monospace; margin: 40px; }
        .container { max-width: 1200px; margin: auto; }
        .header { text-align: center; border-bottom: 2px solid #00ff88; padding-bottom: 20px; }
        .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin: 30px 0; }
        .card { background: #1a1f3a; padding: 20px; border-radius: 10px; border-left: 4px solid #00ff88; }
        .number { font-size: 2em; font-weight: bold; color: #00ff88; }
        .section { background: #0f1433; padding: 20px; border-radius: 10px; margin: 20px 0; }
        h1, h2 { color: #00ff88; }
        pre { background: #1a1f3a; padding: 15px; overflow-x: auto; border-radius: 5px; }
        .critical { color: #ff4444; }
        .high { color: #ff8844; }
        .medium { color: #ffcc44; }
        .footer { text-align: center; padding: 20px; color: #666; border-top: 1px solid #2a2f4a; margin-top: 30px; }
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>🔍 ReconForge Report</h1>
        <p>%s | %s</p>
    </div>
    <div class="summary">
        <div class="card"><h3>🌐 Subdomains</h3><div class="number">%d</div></div>
        <div class="card"><h3>✅ Live Hosts</h3><div class="number">%d</div></div>
        <div class="card"><h3>🔗 URLs</h3><div class="number">%d</div></div>
        <div class="card"><h3>⚠️ Findings</h3><div class="number">%d</div></div>
    </div>
    <div class="section">
        <h2>📋 Live Hosts</h2>
        <pre>%s</pre>
    </div>
    <div class="section">
        <h2>⚠️ Potential Findings</h2>
        <pre>%s</pre>
    </div>
    <div class="footer">
        <p>Generated by ReconForge | Authorized Use Only</p>
    </div>
</div>
</body>
</html>`,
        data.Target,
        data.Target,
        time.Now().Format("2006-01-02 15:04:05"),
        len(data.Subdomains),
        len(data.LiveHosts),
        len(data.URLs),
        len(data.Vulnerabilities),
        strings.Join(data.LiveHosts, "\n"),
        g.formatVulnerabilitiesForHTML(data.Vulnerabilities),
    )
    
    return os.WriteFile(filePath, []byte(htmlContent), 0644)
}

func (g *Generator) formatVulnerabilitiesForHTML(vulns []Vulnerability) string {
    if len(vulns) == 0 {
        return "No vulnerabilities found"
    }
    var result []string
    for _, v := range vulns {
        severityClass := "medium"
        if v.Severity == "CRITICAL" {
            severityClass = "critical"
        } else if v.Severity == "HIGH" {
            severityClass = "high"
        }
        result = append(result, fmt.Sprintf("<span class=\"%s\">[%s]</span> %s: %s (CVSS: %.1f)", severityClass, v.Severity, v.TemplateID, v.Name, v.CVSS))
    }
    return strings.Join(result, "<br>")
}
