package report

import (
    "fmt"
    "os"
    "strings"
    "time"
)

type MarkdownExporter struct {
    outputFile string
}

func NewMarkdownExporter(outputFile string) *MarkdownExporter {
    return &MarkdownExporter{
        outputFile: outputFile,
    }
}

func (m *MarkdownExporter) Export(data *ReportData) error {
    content := fmt.Sprintf(`# ReconForge Scan Report

**Target:** %s
**Date:** %s
**Duration:** %s

## Summary

| Metric | Value |
|--------|-------|
| Subdomains | %d |
| Live Hosts | %d |
| URLs | %d |
| Vulnerabilities | %d |

## Live Hosts

%s

## Vulnerabilities

%s

## Open Ports

%s

## Technologies

%s

---
*Generated by ReconForge v4.0 | Authorized Use Only*
`,
        data.Target,
        time.Now().Format("2006-01-02 15:04:05"),
        data.Duration,
        len(data.Subdomains),
        len(data.LiveHosts),
        len(data.URLs),
        len(data.Vulnerabilities),
        strings.Join(data.LiveHosts, "\n"),
        m.formatVulnerabilities(data.Vulnerabilities),
        m.formatPorts(data.OpenPorts),
        m.formatTechnologies(data.Technologies),
    )
    
    return os.WriteFile(m.outputFile, []byte(content), 0644)
}

func (m *MarkdownExporter) formatVulnerabilities(vulns []Vulnerability) string {
    if len(vulns) == 0 {
        return "No vulnerabilities found"
    }
    var lines []string
    for _, v := range vulns {
        lines = append(lines, fmt.Sprintf("- [%s] %s: %s (CVSS: %.1f)", v.Severity, v.TemplateID, v.Name, v.CVSS))
    }
    return strings.Join(lines, "\n")
}

func (m *MarkdownExporter) formatPorts(ports []Port) string {
    if len(ports) == 0 {
        return "No open ports found"
    }
    var lines []string
    for _, p := range ports {
        lines = append(lines, fmt.Sprintf("- %s:%d (%s)", p.Host, p.Port, p.Service))
    }
    return strings.Join(lines, "\n")
}

func (m *MarkdownExporter) formatTechnologies(techs []Technology) string {
    if len(techs) == 0 {
        return "No technologies detected"
    }
    var lines []string
    for _, t := range techs {
        lines = append(lines, fmt.Sprintf("- %s: %s %s", t.URL, t.Name, t.Version))
    }
    return strings.Join(lines, "\n")
}
